mealplan/urls.py
from django.conf.urls import patterns, include, url

#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'meals.views.home_page', name='home'),

	url(r'^meals/', include('meals.urls')),

    #url(r'^admin/', include(admin.site.urls)),
)

meals/urls.py
from django.conf.urls import patterns, include, url

#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
	url(r'^(\d+)/$', 'meals.views.view_arsenal', name='view_arsenal'),
	url(r'^new$', 'meals.views.new_arsenal', name='new_arsenal'),

    #url(r'^admin/', include(admin.site.urls)),
)

meals/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Arsenal(models.Model):
	
	def get_absolute_url(self):
		return reverse('view_arsenal', args=[self.id])

class Entree(models.Model):
	name = models.TextField()
	arsenal = models.ForeignKey(Arsenal)

	class Meta:
		unique_together = ('arsenal', 'name')

	def __str__(self):
		return self.name

meals/forms.py
from django import forms
from django.core.exceptions import ValidationError

from meals.models import Entree


EMPTY_ENTREE_ERROR = 'Entree names must not be blank'
DUPLICATE_ENTREE_ERROR = 'Entree already added'

class EntreeForm(forms.models.ModelForm):

	class Meta:
		model = Entree 
		fields = ('name',)
		widgets = {
			'name': forms.fields.TextInput(
				attrs={
					'placeholder': 'Enter an entree',
					'class': 'form-control input-lg',
				}),
			}

		error_messages = {
				'name': {'required': EMPTY_ENTREE_ERROR},
			}

	def save(self, for_arsenal):
		self.instance.arsenal = for_arsenal
		return super().save()


class ExistingArsenalEntreeForm(EntreeForm):

	def __init__(self, for_arsenal, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.instance.arsenal = for_arsenal

	def validate_unique(self):
		try:
			self.instance.validate_unique()
		except ValidationError as e:
			e.error_dict = {'name': [DUPLICATE_ENTREE_ERROR]}
			self._update_errors(e)

	def save(self):
		return forms.models.ModelForm.save(self)

meals/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.exceptions import ValidationError

from meals.models import Entree, Arsenal
from meals.forms import EntreeForm, ExistingArsenalEntreeForm

def home_page(request):
	return render(request, 'home.html', {'form': EntreeForm()})

def view_arsenal(request, arsenal_id):
	ars = Arsenal.objects.get(id=arsenal_id)
	form = ExistingArsenalEntreeForm(for_arsenal=ars)

	if request.method == 'POST':
		form = ExistingArsenalEntreeForm(for_arsenal=ars, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect(ars)

	return render(request, 'arsenal.html', {
				'arsenal': ars,
				'form': form,
			})

def new_arsenal(request):
	form = EntreeForm(data=request.POST)
	if form.is_valid():
		ars = Arsenal.objects.create()
		form.save(for_arsenal=ars)
		return redirect(ars)
	else:
		return render(request, 'home.html', {'form':form})

meals/templates/arsenal.html
{% extends 'base.html' %}

{% block header_text %}MealPlan{% endblock %}

{% block form_action %}{% url 'view_arsenal'  arsenal.id %}{% endblock %}

{% block table %}
	<table id="id_entree_table" class="table">
		{% for entree in arsenal.entree_set.all %}
		<tr><td>{{ entree.name }} (entree)</td></tr>
		{% endfor %}
	</table>
{% endblock %}

meals/templates/base.html
<html>
	<head>
		<title>MealPlan</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
		<link href="/static/base.css" rel="stylesheet" media="screen">
	</head>
	<body>
	<div class="container">

		<div class="row">
			<div class="col-md-6 col-md-offset-3 jumbotron">
				<div class="text-center">
					<h1>{% block header_text %}{% endblock %}</h1>
					<form method="POST" action="{% block form_action %}{% endblock %}">
						{% csrf_token %}
						{% if form.errors %}
							<div class="form-group has-error">
								<span class="help-block">{{ form.name.errors }}</span>
							</div>
						{% endif %}
						{{ form.name }}
					</form>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				{% block table %}
				{% endblock %}
			</div>
		</div>

	</div>
	</body>
</html>

meals/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new MealPlan{% endblock %}

{% block form_action %}{% url 'new_arsenal' %}{% endblock %}

meals/templates/meals.html
<html>
	<head>
		<title>MealPlan</title>
	</head>
	<body>
		<h1>MealPlan</h1>
		<form method="POST" action="/meals/{{ arsenal.id }}/new_entree">
			{% csrf_token %}
			<input name="entree_name" id="id_new_entree" placeholder="Enter an entree" />
		</form>
		<table id="id_entree_table">
			{% for entree in arsenal.entree_set.all %}
				<tr><td>{{ entree.name }} (entree)</td></tr>
			{% endfor %}
		</table>
	</body>
</html>